logging:
  file:
    path: logs
github:
  owner: owner
  repo: repo
  scope: true
  token: token
artifact:
  name: artifact.zip
shell:
  path: /blog_artifact_update.sh
  name: blog
  nginx: /blog
  artifact: /artifact.zip
